### ISSUE TITLE
Format raw data in "show" command using go-whosonfirst-format-wasm

### ISSUE THREAD

**Issue by straup** [whosonfirst/wof-cli#6]
Note, this will require iterating through the items in the FeatureCollection returned by the server because `go-whosonfirst-format-wasm` only works with `Feature` elements.

* https://github.com/whosonfirst/go-whosonfirst-format-wasm
* https://github.com/whosonfirst/wof-cli/blob/main/show/www/javascript/show.js#L20-L23

**Comment by thisisaaronland** [comment]
Blocked on https://github.com/whosonfirst/go-whosonfirst-format-wasm/issues/1

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/go-whosonfirst-format-wasm?tab=readme-ov-file#wasm-javascript

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/wof-cli/releases/tag/v0.0.6
